"""Remove Task relationship from User

Revision ID: 3cbccadbba68
Revises: b02ab4e383e2
Create Date: 2024-11-05 14:09:05.232061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbccadbba68'
down_revision: Union[str, None] = 'b02ab4e383e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
