"""Initial migration

Revision ID: dac5e1e0f0f7
Revises: b8f8650aafd3
Create Date: 2024-10-13 01:27:16.534216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dac5e1e0f0f7'
down_revision: Union[str, None] = 'b8f8650aafd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
